chas-academy/u08-business-idea-team1-bokmalarna

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/addbook/Addbook.js
- frontend/src/components/bookpage/Bookpage.js
- frontend/src/components/dashboard/Dashboard.js
- frontend/src/components/login/Login.js
- frontend/src/components/registration/Registration.js
- frontend/src/components/search/Search.js
- frontend/src/index.js
- package-lock.json
Add components and fix routing #30 #25 #28 #29 #27 #24 #26
> Regandlogincomponents

- backend/routes/user.js
> Registration

- backend/package-lock.json
- backend/package.json
- backend/routes/user.js
> Add hashed password

- backend/package-lock.json
- backend/package.json
- backend/routes/user.js
- backend/server.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/dashboard/Dashboard.js
- frontend/src/components/login/Login.js
Created a view in frontend without styling !!. This will let user login and log out. Redirect not included yet.
> React login/logout

- backend/models/user.js
> Remove confirm password from model

- backend/routes/user.js
Api for letting a user delete her/his account is done. Api will take the id form the params and check if the id exists in the database. If it dose it will remove it otherwise send a message that that specific id dosent exist in the DB.
> create delete api response to let user delete its account with id

- frontend/src/components/addbook/Addbook.js
Reverts chas-academy/u08-business-idea-team1-bokmalarna#71
> Revert "add styling to addBook component"

- frontend/src/components/search/Search.js
This PR will implement a static representation for the search site
> Create static website for search

- backend/models/book.js
> fix bookmodel to be type: Date on released

- backend/routes/user.js
This PR will add more user info for JWT token so that we can get all the information from the user to the FE.
New route is added: /user/protected and will let a user with a valid JWT token access the dashboard.
Issue: #90
> User route be

- frontend/src/components/Home/Home.js
> 93 fix text format landingpage

- backend/routes/book.js
This PR will fix a route to let User fetch his/hers books.
Issues: #99
> Create a get route to let a users fetch its books

- backend/controllers/bookController.js
- backend/package-lock.json
- backend/package.json
- backend/routes/book.js
Changed the issue a bit, because the image upload connected to create book was easier to do it all in BE
(Previous name of issue: "Create image for book in BE"
Issue #64
> Post book be img

- frontend/src/components/dashboard/Dashboard.js
- frontend/src/components/login/Login.js
- frontend/src/components/registration/Registration.js
> update API_URLs and set DEV/PROD URL for server.js

- backend/server.js
- frontend/src/components/footer/Footer.js
This PR will hopefully fix cors problems
> Server fixes

- backend/server.js
- frontend/src/App.js
- frontend/src/components/login/Login.js
This PR Will fix some functionality for the Navbar and make the text bold
Issue: #126
> Navbar fix

- backend/.gitignore
- frontend/src/components/dashboard/Dashboard.js
This PR will show all users books that she/he has created and let them delete them or one of them.
Issues #144 #146
> Get user books

- frontend/src/App.js
- frontend/src/index.css
This PR will change color to white, remove dropdown, change background color in navbar and changing fontstyle.
Issues: #132 + #137
> Fix colours in app

- frontend/src/components/login/Login.js
This PR will style the login component Frontend and add a useEffect to check if user is already logged in, the user should not be able to log in again.
Issue: #149
> Fix login style

- backend/routes/book.js
- frontend/src/components/dashboard/Dashboard.js
- readme.md
This PR will let users fetch its borrowed books and see them in Dashboard.
Issue: #152
> Get all users borrowed books

- frontend/src/components/Home/Home.js
- frontend/src/index.css
> layout problem fix in mobile view and desktop

- frontend/src/components/login/Login.js
- frontend/src/components/registration/Registration.js
- Add alerts when login fails and registration is successfull
> Alerts n stuf

- backend/routes/book.js
- frontend/src/components/search/Search.js
> Search form

- frontend/src/components/Home/Home.js
- frontend/src/components/registration/Registration.js
This PR will change:
1. Layout of the component/site
2. The  user will be navigated to Login page after registered
3. Log In + Register will now be links in dashboard
Issues: #172 #170 #169
> Fix register component

- backend/routes/book.js
This PR will make get single book route to send users location
issue: #218
> make single book api send users city

- backend/routes/user.js
- frontend/src/components/edit/Edit.js
> 179 reset password

- backend/models/book.js
- frontend/src/components/addbook/Addbook.js
This PR will fix addbok so it will send released date aswell.
issue: #226
> Fix addbook

- backend/routes/user.js
- frontend/src/components/edit/Edit.js
- frontend/src/components/edit/edit.css
> 231 add alert message on password reset

- backend/routes/book.js
- backend/routes/user.js
- backend/socket/index.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/addbook/Addbook.js
- frontend/src/components/bookpage/Bookpage.js
- frontend/src/components/dashboard/Dashboard.js
- frontend/src/components/edit/Edit.js
- frontend/src/components/edit/Editbook.js
- frontend/src/components/edit/edit.css
- frontend/src/components/footer/Footer.js
- frontend/src/components/login/Login.js
- frontend/src/components/registration/Registration.js
- frontend/src/components/search/Search.js
- frontend/src/index.js
This PR will hopefully fix most of the beta bugs!
Issue: #237 #205 #216 #238
> Fix terminal warnings
